FROM atendai/evolution-api:2.0.15

# Disable all database and storage
ENV DATABASE_ENABLED=false
ENV DATABASE_PROVIDER=""
ENV DATABASE_CONNECTION_URI=""
ENV REDIS_ENABLED=false
ENV REDIS_URI=""

# Disable all storage
ENV STORE_MESSAGES=false
ENV STORE_CONTACTS=false
ENV STORE_CHATS=false
ENV STORE_PRESENCE=false
ENV STORE_SETTINGS=false

# Server configuration
ENV SERVER_URL=https://evolution-api-whatsapp.onrender.com
ENV LOG_LEVEL=ERROR
ENV CORS_ORIGIN=*

# Webhook configuration
ENV WEBHOOK_GLOBAL_URL=https://hndll.app.n8n.cloud/webhook/evolution-webhook
ENV WEBHOOK_GLOBAL_ENABLED=true
ENV WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
ENV WEBHOOK_GLOBAL_EVENTS="MESSAGES_UPSERT,MESSAGES_UPDATE,MESSAGES_DELETE,SEND_MESSAGE,CONTACTS_SET,CONTACTS_UPSERT,CONTACTS_UPDATE,PRESENCE_UPDATE,CHATS_SET,CHATS_UPSERT,CHATS_UPDATE,CHATS_DELETE,GROUPS_UPSERT,GROUP_UPDATE,GROUP_PARTICIPANTS_UPDATE,CONNECTION_UPDATE,CALL,NEW_JWT_TOKEN"

EXPOSE 8080

CMD ["node", "/evolution/dist/src/main.js"]
